name: Feature request
description: Create a feature request to help us improve
labels:
  - feature
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Add any additional info you think might be helfpul.
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to the terms below.
      options:
        - label: I am reporting an issue for CapOS, not an unsupported fork.
        - label: I am certain that the feature I'm requesting is not yet available in CapOS.
        - label: I am certain that there are no other issues with content that highly overlaps with this one.
          required: true
