
include $(TOPDIR)/rules.mk

LUCI_TYPE:=col
LUCI_BASENAME:=capos-full
PKG_RELEASE:=1

LUCI_TITLE:=CapOS Full
LUCI_DESCRIPTION:=CapOS Full Collection
LUCI_DEPENDS:= \
	+capos-web-desktop \
	+capos-standard \

PKG_LICENSE:=Apache-2.0

include $(INCLUDE_DIR)/package.mk
