
include $(TOPDIR)/rules.mk

LUCI_TYPE:=col
LUCI_BASENAME:=capos-standard
PKG_RELEASE:=1
PKG_MAINTAINER:=FWERKOR Team

LUCI_TITLE:=CapOS Standard
LUCI_DESCRIPTION:=CapOS Standard Collection
LUCI_DEPENDS:= \
	+capos-web-desktop \

PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/rules.mk
include $(INCLUDE_DIR)/kernel.mk
include $(INCLUDE_DIR)/version.mk
include $(INCLUDE_DIR)/feeds.mk
include $(INCLUDE_DIR)/package.mk
