
include $(TOPDIR)/rules.mk

LUCI_TYPE:=col
LUCI_BASENAME:=capos-standard
PKG_RELEASE:=1

LUCI_TITLE:=CapOS Standard
LUCI_DESCRIPTION:=CapOS Standard Collection
LUCI_DEPENDS:= \
	+capos-web-desktop \
	+luci \

PKG_LICENSE:=Apache-2.0

include $(INCLUDE_DIR)/package.mk
